version: '3'
networks:
  symfony:
    driver: bridge
services:
  mariadb:
    image: mariadb:10.4.33
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caretakerservicesdb
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pass
    ports:
      - 3311:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - symfony
  app-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: app-api
    ports:
      - 8050:8050
    volumes:
      - ./CaretakerServicesApi:/usr/share/nginx/html/CaretakerServicesApi
      - /home/webadmin/default-api.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
    environment:
      DATABASE_URL: "mysql://root:root@mariadb:3306/caretakerservicesdb"
  app-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web
    ports:
      - 8060:8060
    volumes:
      - ./CaretakerServicesWeb:/usr/share/nginx/html/CaretakerServicesWeb
      - /home/webadmin/default-web.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
volumes:
  mariadb_data: