version: '3.8'

services:
  web:
    build:
      context: ./CaretakerServicesWeb
      dockerfile: Dockerfile.web
    container_name: web
    volumes:
      - ./CaretakerServicesWeb:/var/www/html
      - ./certs:/etc/apache2/ssl
    ports:
      - "8090:80"
      - "7443:443"
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=caretakerservices.fr
      - LETSENCRYPT_HOST=caretakerservices.fr
      - LETSENCRYPT_EMAIL=your-email@example.com

  api:
    build:
      context: ./CaretakerServicesApi
      dockerfile: Dockerfile.api
    container_name: api
    volumes:
      - ./CaretakerServicesApi:/var/www/html
      - ./certs:/etc/apache2/ssl
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=api.caretakerservices.fr
      - LETSENCRYPT_HOST=api.caretakerservices.fr
      - LETSENCRYPT_EMAIL=your-email@example.com

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caretakerservicesdb
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
