version: '3.8'

networks:
  symfony:
    driver: bridge

services:
  web:
    build:
      context: ./CaretakerServicesWeb
      dockerfile: Dockerfile.web
    container_name: web
    volumes:
      - ./CaretakerServicesWeb:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/webadmin/.env-web:/var/www/html/.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=caretakerservices.fr
      - LETSENCRYPT_HOST=caretakerservices.fr
      - LETSENCRYPT_EMAIL=leopold.goudier@gmail.com
    networks:
      - symfony

  api:
    build:
      context: ./CaretakerServicesApi
      dockerfile: Dockerfile.api
    container_name: api
    volumes:
      - ./CaretakerServicesApi:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/webadmin/jwt:/var/www/html/config/jwt
      - /home/webadmin/.env-api:/var/www/html/.env
    ports:
      - "8080:80"
      - "4443:443"
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=api.caretakerservices.fr
      - LETSENCRYPT_HOST=api.caretakerservices.fr
      - LETSENCRYPT_EMAIL=leopold.goudier@gmail.com
    networks:
      - symfony

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caretakerservicesdb
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - symfony

volumes:
  mariadb_data:
