FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
    libicu-dev \
    libpq-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install \
    intl \
    pdo \
    pdo_mysql \
    zip

COPY apache/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite ssl

EXPOSE 80 443
