FROM httpd:2.4

RUN apt-get update && apt-get install -y \
    vim \
    && a2enmod proxy \
    && a2enmod proxy_http \
    && a2enmod ssl

COPY apache/proxy.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 80 443
