name: Deploy to Linux Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/html/PA
          git fetch origin dev
          git reset --hard origin/dev

          docker build --target api -t mon-api .
          docker run -p 4443:4443 --name app-api -d mon-api
          docker exec -it app-api /bin/sh -c "symfony server:start --port=4443"

          docker build --target web -t mon-web .
          docker run -p 443:443 --name app-web -d mon-web
          docker exec -it app-web /bin/sh -c "symfony server:start --port=443"
