name: Deploy to Linux Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          # sudo chown -R $USER:$USER /var/www/html/PA
          # sudo chmod -R 755 /var/www/html/PA

          cd /var/www/html/PA

          git config --global --add safe.directory /var/www/html/PA

          git fetch origin dev
          git reset --hard origin/dev

          sudo usermod -aG docker $USER || true
          sudo chmod 666 /var/run/docker.sock

          docker stop app-api || true
          docker rm app-api || true
          docker stop app-web || true
          docker rm app-web || true

          docker build --target api -t mon-api .
          docker run -p 80:443 --name app-api -d mon-api || docker start app-api
          docker cp /home/webadmin/default.conf app-api:/etc/nginx/conf.d/default.conf
          docker exec -d app-api /bin/sh "composer install"
          docker exec -d app-api /bin/sh "symfony server:start"

          # docker build --target web -t mon-web .
          # docker run -p 443:443 --name app-web -d mon-web || docker start app-web
          # docker exec -d app-web /bin/sh -c "symfony server:start --port=443"
